"""Initial migration.

Revision ID: aee01594ded1
Revises: 
Create Date: 2021-06-30 12:08:46.314310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee01594ded1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_1', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('module_2', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('module_3', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('module_4', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_4', 'completed')
    op.drop_column('module_3', 'completed')
    op.drop_column('module_2', 'completed')
    op.drop_column('module_1', 'completed')
    # ### end Alembic commands ###
